name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Installing needed Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        components: clippy,rustfmt

    - name: Run formatter and lint
      run: cargo fmt -- --check && cargo clippy -- -D warnings

    - name: Build
      run: cargo build --release --target=${{ matrix.target }}

    - name: Tests
      run: cargo test
      continue-on-error: ${{ matrix.rust == 'nightly' }}
