name: Upload to release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target=${{ matrix.target }} --bin passwd-gen

      - name: Rename release binary ${{ matrix.os }}
        if: matrix.os == 'ubuntu-latest'
        run: mv target/${{ matrix.target }}/release/passwd-gen target/${{ matrix.target }}/release/${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.target }}-passwd-gen.out

      - name: Rename release binary ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: mv target/${{ matrix.target }}/release/passwd-gen.exe target/${{ matrix.target }}/release/${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.target }}-passwd-gen.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release//${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.target }}-passwd-gen.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
